image:
  repository: your-docker-repo/bezkoder-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  DB_HOST: mysql-service
  DB_USER: root
  DB_PASSWORD: yourpassword
