apiVersion: apps/v1
kind: Deployment
metadata:
  name: bezkoder-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bezkoder-app
  template:
    metadata:
      labels:
        app: bezkoder-app
    spec:
      containers:
      - name: bezkoder-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "{{ .Values.env.DB_HOST }}"
        - name: DB_USER
          value: "{{ .Values.env.DB_USER }}"
        - name: DB_PASSWORD
          value: "{{ .Values.env.DB_PASSWORD }}"
